version: '3.8'

services:
  graphi:
    image: ${CI_REGISTRY_IMAGE}:latest
    container_name: tools-graphi
    restart: always
    networks:
      - aitools_net

networks:
  aitools_net:
    external: true
